import React from 'react';
import { MessageCircle, Shield, Lock, AlertTriangle } from 'lucide-react';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 to-gray-800">
      <div className="max-w-4xl mx-auto p-6 pt-12">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="flex justify-center">
            <MessageCircle className="h-12 w-12 text-blue-400" />
          </div>
          <h1 className="mt-4 text-4xl font-bold text-white">Deepthink Terms of Service & Privacy Policy</h1>
          <p className="mt-2 text-gray-300">Last Updated: January 16, 2025</p>
        </div>

        {/* Main Content */}
        <div className="space-y-8 bg-white rounded-xl shadow-2xl p-8">
          {/* Introduction */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
              <Shield className="h-6 w-6 mr-2 text-blue-600" />
              Introduction
            </h2>
            <p className="text-gray-600 mb-4">
              Welcome to Deepthink ("Service"), an AI-powered chatbot platform utilizing the Qwen 2.5 model from Hugging Face, 
              fine-tuned specifically for coding problems. By accessing or using our Service, you agree to be bound by these 
              Terms of Service and Privacy Policy.
            </p>
          </section>

          {/* Eligibility */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Age Restrictions</h2>
            <p className="text-gray-600 mb-4">
              You must be at least 13 years of age to use this Service. If you are under 13 years old, please do not use 
              or access the Service at any time or in any manner.
            </p>
          </section>

          {/* Data Collection and Privacy */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
              <Lock className="h-6 w-6 mr-2 text-blue-600" />
              Data Collection and Privacy
            </h2>
            <div className="space-y-4 text-gray-600">
              <p>
                We collect and store your chat history and related data for the purpose of providing and improving our Service. 
                Specifically:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Chat history is retained for the duration of your login session</li>
                <li>Data is encrypted and stored on PythonAnywhere.com servers located in the United States</li>
                <li>We use this data to maintain conversation context and improve user experience</li>
                <li>You can access your chat history while logged in</li>
              </ul>
            </div>
          </section>

          {/* Service Usage */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Service Usage and Limitations</h2>
            <div className="space-y-4 text-gray-600">
              <p>
                The Service is currently provided free of charge with no usage limits. However:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>We reserve the right to modify or implement usage limits in future updates</li>
                <li>The Service is provided "as is" for development and early release purposes</li>
                <li>Commercial use is not recommended or supported</li>
                <li>All outputs generated by our AI model are provided under a Creative Commons CC BY-SA 4.0 license</li>
              </ul>
            </div>
          </section>

          {/* Disclaimers */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4 flex items-center">
              <AlertTriangle className="h-6 w-6 mr-2 text-blue-600" />
              Disclaimers and Limitations
            </h2>
            <div className="space-y-4 text-gray-600">
              <p>
                As a development and early release product:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>We are not responsible for any loss of information or damages resulting from use of the Service</li>
                <li>We do not guarantee uninterrupted, secure, or error-free operation</li>
                <li>The Service should not be used for critical or commercial applications</li>
                <li>We are not responsible for any misuse of the Service, including but not limited to criminal activity, 
                    abuse, or harassment</li>
                <li>Content moderation features are under development and will be implemented in future updates</li>
              </ul>
            </div>
          </section>

          {/* Contact Information */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Contact Information</h2>
            <p className="text-gray-600 mb-4">
              For any questions or concerns regarding these terms or the Service, please contact us at:{' '}
              <a href="mailto:jahanzebahmed.mail@gmail.com" className="text-blue-600 hover:text-blue-500">
                jahanzebahmed.mail@gmail.com
              </a>
            </p>
          </section>

          {/* Updates to Terms */}
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Updates to Terms</h2>
            <p className="text-gray-600 mb-4">
              We reserve the right to modify these terms at any time. We will notify users of any material changes through 
              the Service or via email. Continued use of the Service after such modifications constitutes acceptance of the 
              updated terms.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="text-center mt-8 text-gray-400 text-sm">
          <p>© 2025 Deepthink. All rights reserved.</p>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
